APP_NAME=ERP
APP_ENV=local
APP_KEY=base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
APP_DEBUG=true
APP_URL=http://localhost:8080

LOG_CHANNEL=stack
LOG_LEVEL=debug

DB_CONNECTION=pgsql
DB_HOST=127.0.0.1
DB_PORT=5432
DB_DATABASE=erp
DB_USERNAME=postgres
DB_PASSWORD=postgres

CACHE_DRIVER=redis
QUEUE_CONNECTION=sync
SESSION_DRIVER=array

REDIS_CLIENT=predis
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
STOMP_REDIS_CHANNEL=erp.stomp
STOMP_PORT=8090

JWT_ISSUER=erp
JWT_SECRET=dev-secret-change-me-in-production-must-be-long-enough-for-hmac-sha256
JWT_ACCESS_TTL_SECONDS=900
JWT_REFRESH_TTL_SECONDS=1209600

CORS_ALLOWED_HOSTS=*
CORS_ALLOWED_METHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
CORS_ALLOWED_HEADERS=*

RATE_LIMIT_ENABLED=true
RATE_LIMIT_PER_MINUTE=120
AUTH_RATE_LIMIT_PER_MINUTE=20

BROADCAST_DRIVER=pusher
PUSHER_APP_ID=erp-local
PUSHER_APP_KEY=erp-local-key
PUSHER_APP_SECRET=erp-local-secret
PUSHER_APP_CLUSTER=mt1
PUSHER_HOST=127.0.0.1
PUSHER_PORT=6001
PUSHER_SCHEME=http
LARAVEL_WEBSOCKETS_PORT=6001

STREAM_API_KEY=4jgpsany48vw
STREAM_API_SECRET=dahx3mgg5pcpyg4m8kwtre5yvy7f2rsv9zca38na9a4jenwza8sac49pcunk72pf
STREAM_TOKEN_TTL_MINUTES=60

FCM_ENABLED=false
FCM_SERVICE_ACCOUNT_JSON_PATH=

CHAT_CALL_RING_TIMEOUT_SECONDS=60
CHAT_CALL_ACCEPT_GRACE_SECONDS=5
CHAT_CALL_SWEEP_INTERVAL_MS=5000

UPLOAD_AVATAR_DIR=./uploads/avatars
UPLOAD_AVATAR_PUBLIC_BASE_URL=/uploads/avatars
UPLOAD_AVATAR_MAX_SIZE=5242880
UPLOAD_AVATAR_ALLOWED_TYPES=image/jpeg,image/png,image/webp
